<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>Assets/duck-minimalist.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="wwwroot/assets/duck-minimalist.ico" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="MySql.Data" Version="9.7.0" />
    <PackageReference Include="MySqlConnector" Version="2.6.1" />
  </ItemGroup>

</Project>
